### ISSUE TITLE
candidate pipes for strict text

### ISSUE THREAD

**Issue by michaelt** [GregorySchwartz/fasta#1]
Hi, I came across this, and wondered if the pipes functions at the end of this https://gist.github.com/michaelt/cfd97dea2a255235e2fc looked reasonable. The 'parsing' is by the equivalent of Data.List operations, and probably includes some mistakes.

**Comment by GregorySchwartz** [comment]
I already pushed a version that works by folding each Producer into a Text and mapping a basic fasta transformation on that text. While it takes very little code to write, it has the issue where the folding loads the entire fasta entry into memory which may result in crash and burns on very very long entries. The best way to compare these two would be to benchmark. For now I'll close this issue, but if it turns out that your method is much faster and memory efficient I'll make the switch.

**Comment by GregorySchwartz** [comment]
Benchmark needed to replace existing method

**Comment by michaelt** [comment]
Ah, cool. There is a dumb error in the gist I pasted, but I just repaired it. Are you making a giant Text out of each file? The gist won't do that, but it will accumulate a big strict text for the individual 'FastaSequence'.

**Comment by GregorySchwartz** [comment]
Yeah, that's what I'm doing right now. It makes a giant Text for each ">" split and converts that Text to a single FastaSequence. Essentially it's modeled after the solution to http://stackoverflow.com/questions/25982213/using-haskell-pipes-bytestring-to-iterate-a-file-by-line. From the sound of it, I think you might be doing the same thing in a different fashion, right? Or do you find away around to have everything continue to stream?

**Comment by michaelt** [comment]
I'm doing the same: turning a a Text producer into FastaSequences where the the whole fastaSeq is one big strict text. The memory problem is built into the FastaSequence type for strict text, though, however you handle it - or am I not understanding? You could work with a semi-serialized type like the Chunk type I use (as I do inside a couple of functions). Maybe it's a little crazy, but you could also define a Pipes-ish FastaSequence type: 

```
  data FastaSequence m r = FastaSequence {fastaHeader :: T.Text, fastaSeq :: Producer T.Text m r}
```

or similarly for a bytestring representation. Then you would have something like 

```
  sequenceHandle :: MonadIO m => IO.Handle -> FreeT (FastaSequence m) m r 
```

Then you could e.g. 'maps' operations on such FastaSequences and so forth. That would involve another level of mental strain, of course, but there would never be a memory problem anywhere.  I'm not sure how you would handle the clone map business with that approach though.

**Comment by GregorySchwartz** [comment]
Yes, that might a bit too unorthodox to implement as I would assume that if one worked with a very large fasta sequence, that would be split up by gene, chromosome, ANYTHING that would not result in gigabytes worth of a single sequence. So I'll keep it all as a string, text, or lazy text.

**Comment by michaelt** [comment]
Right, if it is possible to keep the `fastaSeq` in any `FastaSequence` below a certain size, then this will make sense. I was just wondering if that could be counted on. I also wondered by the way, why you didn't consider just using ByteString for the `fastaSeq` field? This is a little distasteful, but it seems that the files never contain letters outside 

```
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFG
HIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmn
opqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·
¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛ
```

so there shouldn't be trouble representing things with ByteString, using the otherwise crass Char8 interface for literals and counting and so on. This cuts the memory used by the field in half since Text represents these characters by a Word16 http://blog.johantibell.com/2011/06/memory-footprints-of-some-common-data.html It also has the advantage of avoiding the necessity of decoding, of course.

**Comment by GregorySchwartz** [comment]
So I was thinking about bytestrings a long time ago and ultimately made the decision to just include Data.Text as in my research it looked like Bytestring was recommended for binary data, whereas Text was recommended for any human readable text. In addition, I've seen people put crazy characters in the headers of fasta files. It's a good thought though and it should be quick to implement just in case anyone wants to use it as they don't need Text.

**Comment by michaelt** [comment]
Yeah, that's my understanding too, but I was thinking the sequences themselves are in some no-man's land between binary files and 'real' text, so the size and efficiency considerations might tip the balance against fastidious use of Text.  When I thought of it, looking at this the other day, I wondered if it wouldn't be a good idea to make the header field Text anyway: it isn't the main size issue, and the main thing you calculate with, the fastaSeq field is. If they are using the Russian alphabet and the like sometimes,  then clearly it would have to be Text. But I take it this is only in the header?  I don't know if it would make things appreciably more unpleasant and error prone when it came to writing whatever calculations you want to do with the sequences.

**Comment by GregorySchwartz** [comment]
I implemented Data.Fasta.ByteString and Lazy versions. They seem to be working well and I'll see how well they perform on my big data projects versus the text versions.
